use_frameworks!

platform :ios, '9.0'

target 'customPodGlobalClass_Example' do
  pod 'customPodGlobalClass', :path => '../'

  target 'customPodGlobalClass_Tests' do
    inherit! :search_paths

    
  end
end
